name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm install xlsx js-yaml

      - name: Generate Excel file
        run: node generate-excel.js

      - name: Upload Excel file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated_excel
          path: generated_data.xlsx

      - name: Send email on success
        if: success()  # This ensures the email is only sent if the previous steps succeed
        uses: mschwarz/send-mail@v1
        with:
          smtp-server: smtp.qq.com
          smtp-port: 587
          smtp-username: ${{ secrets.EMAIL_USERNAME }}  # GitHub Secrets for email username
          smtp-password: ${{ secrets.EMAIL_PASSWORD }}  # GitHub Secrets for email password
          to: 1761997923@qq.com  # Email recipient
          from: ${{ secrets.EMAIL_USERNAME }}  # The sender email (use the same as SMTP username)
          subject: "GitHub Actions Workflow Succeeded"
          body: "The workflow has completed successfully."
