name: CI Pipeline

on:
  push:
  schedule:
    - cron: '0 1 * * *'  # 每天早上 9 点触发一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # newman: required node version >=16

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      # Run Postman collection using newman
      - name: newman run collection.json
        run: |
          newman run apiFiles/API.postman_collection.json -e apiFiles/openapijs.postman_environment.json -r json,html --reporter-json-export output.json --reporter-html-export output.html

      # Upload the output files as artifacts
      - name: Upload Postman report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: |
            output.json
            output.html

      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # 从 Secrets 中读取 QQ 邮箱地址
          password: ${{ secrets.EMAIL_PASSWORD }}  # 从 Secrets 中读取授权码
          from: ${{ secrets.EMAIL_USERNAME }}  # 发件人邮箱地址
          to: ${{ secrets.EMAIL_USERNAME }}   # 收件人邮箱地址
          subject: "每日测试运行成功"
          body: |
            测试成功，请查看以下链接获取详细信息：
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          secure: true  # 使用 SSL/TLS

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # 从 Secrets 中读取 QQ 邮箱地址
          password: ${{ secrets.EMAIL_PASSWORD }}  # 从 Secrets 中读取授权码
          from: ${{ secrets.EMAIL_USERNAME }}  # 发件人邮箱地址
          to: ${{ secrets.EMAIL_USERNAME }}   # 收件人邮箱地址
          subject: "每日测试运行失败"
          body: |
            测试失败，请查看以下链接获取详细信息：
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          secure: true  # 使用 SSL/TLS
