name: CI Pipeline

on:
  # push: # 测试的时候才放开
  schedule:
    - cron: '0 1 * * *'  # 每天早上 9 点触发一次

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: [openapijs, github]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # newman: 需要 node 版本 >=16

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      # 使用Newman执行多个collection文件
      - name: Run Postman collection
        run: |
          newman run apiFiles/${{ matrix.collection }}.postman_collection.json -e apiFiles/${{ matrix.collection }}.postman_environment.json -r json,html --reporter-json-export output-${{ matrix.collection }}.json --reporter-html-export output-${{ matrix.collection }}.html

      # 生成的文件
      - name: Upload Postman report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports-${{ matrix.collection }} # 给每个集合生成不同的artifact名称
          path: |
            output-${{ matrix.collection }}.json
            output-${{ matrix.collection }}.html

  send-email-success:
    runs-on: ubuntu-latest
    needs: run-newman-tests  # 表示这个作业依赖于 run-newman-tests 作业
    if: success()
    steps:
      # 发送邮件
      - name: Send email on success
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # 从 Secrets 中读取 QQ 邮箱地址
          password: ${{ secrets.EMAIL_PASSWORD }}  # 从 Secrets 中读取授权码
          from: ${{ secrets.EMAIL_USERNAME }}  # 发件人邮箱地址
          to: ${{ secrets.EMAIL_USERNAME }}   # 收件人邮箱地址
          subject: "每日测试运行成功"
          body: |
            测试成功，请查看以下链接获取详细信息：
            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">点击这里查看详细信息</a>
          secure: true  # 使用 SSL/TLS

  send-email-failure:
    runs-on: ubuntu-latest
    needs: run-newman-tests  # 表示这个作业依赖于 run-newman-tests 作业
    if: failure()
    steps:
      - name: Send email on failure
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # 从 Secrets 中读取 QQ 邮箱地址
          password: ${{ secrets.EMAIL_PASSWORD }}  # 从 Secrets 中读取授权码
          from: ${{ secrets.EMAIL_USERNAME }}  # 发件人邮箱地址
          to: ${{ secrets.EMAIL_USERNAME }}   # 收件人邮箱地址
          subject: "每日测试运行失败"
          body: |
            测试失败，请查看以下链接获取详细信息：
            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">点击这里查看详细信息</a>
          secure: true  # 使用 SSL/TLS
