name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install
        run: npm install xlsx js-yaml

      - name: Generate Excel file
        run: node generate-excel.js

      - name: Upload Excel file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated_excel
          path: generated_data.xlsx
